services:
  developer-edition:
    build: .\developer-edition
    # command: -t mssqlserver-2022-developer-cu15-windows:v1.0 --build-arg VERSION=16.00.1000.06
    restart: always
    ports:
      - 3341:49159
      # - 3341:1433
    volumes:
      - D:\databases\developer:C:\databases
    image: microsoft-sqlserver-2022-developer-edition:2022-CU15-v1.1.2
    dockerfile: .\developer-edition\dockerfile
  express-edition:
    build: .\express-edition
    # command: -t mssqlserver-2022-express-cu15-windows:v1.0 --build-arg VERSION=16.00.1000.06
    restart: always
    ports:
      - 3342:49160
      # - 3342:1433
    volumes:
      - D:\databases\express:C:\databases
    image: microsoft-sqlserver-2022-express-edition:2022-CU15-v1.1.2
    dockerfile: .\express-edition\dockerfile
