services:
  mssqlserver-2022-developer-cu15-windows:
    build: .\
    command: "-t mssqlserver-2022-developer-cu15-windows:v1.0 --build-arg VERSION=16.0.4541.4 --build-arg TYPE=dev"
    restart: always
    ports:
      - 1433:1433
    volumes:
      - C:/
    #image: mssqlserver-2022-developer-cu15-windows
    #container-name: mssqlserver-2022-developer-cu15-windows
    #depends_on: 
    #  - mcr.microsoft.com/windows/servercore:ltsc2022